# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mfuip.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_3(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1088, 657)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 200, 1021, 321))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"border-radius: 25px;\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(560, 180, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"border-radius: 25px;\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.label_4.setObjectName("label_4")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 570, 341, 80))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_9)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(440, 50, 191, 25))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 1131, 681))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(890, 550, 160, 89))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"\n"
"\n"
"    \n"
"    \n"
"\n"
"    \n"
"    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.0696517 rgba(91, 102, 65, 0), stop:0.363184 rgba(80, 80, 80, 80), stop:0.587065 rgba(130, 130, 130, 156), stop:0.616915 rgba(255, 255, 255, 80), stop:0.686567 rgba(255, 255, 255, 80), stop:1 rgba(255, 255, 255, 0));\n"
"    \n"
"    \n"
"    \n"
" /* 设置背景颜色 */ \n"
"    \n"
" /* 设置边框颜色和厚度 */ border-radius: 20px; /* 设置圆角半径，数值可根据按钮大小调整 */ padding: 5px 10px; /* 设置内边距 */ \n"
"color: black; /* 设置文本颜色 */ \n"
"font-size: 14px; /* 设置字体大小 */ }\n"
"\n"
"\n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.0696517 rgba(0, 0, 0, 206), stop:0.363184 rgba(11, 40, 79, 80), stop:0.616915 rgba(49, 91, 255, 80), stop:0.686567 rgba(0, 36, 73, 80), stop:0.810945 rgba(0, 25, 82, 156), stop:1 rgba(255, 255, 255, 0));\n"
"color: black; /* 设置鼠标悬停时的文本颜色 */ \n"
"box-shadow: 5px 5px 10px rgba(10, 10, 255, 10); /* 设置鼠标悬停时的阴影效果 */ \n"
"cursor: pointer; /* 设置鼠标悬停时的指针样式 */ } \n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"\n"
"\n"
"    \n"
"    \n"
"\n"
"    \n"
"    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.0696517 rgba(91, 102, 65, 0), stop:0.363184 rgba(80, 80, 80, 80), stop:0.587065 rgba(130, 130, 130, 156), stop:0.616915 rgba(255, 255, 255, 80), stop:0.686567 rgba(255, 255, 255, 80), stop:1 rgba(255, 255, 255, 0));\n"
"    \n"
"    \n"
"    \n"
" /* 设置背景颜色 */ \n"
"    \n"
" /* 设置边框颜色和厚度 */ border-radius: 20px; /* 设置圆角半径，数值可根据按钮大小调整 */ padding: 5px 10px; /* 设置内边距 */ \n"
"color: black; /* 设置文本颜色 */ \n"
"font-size: 14px; /* 设置字体大小 */ }\n"
"\n"
"\n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.0696517 rgba(0, 0, 0, 206), stop:0.363184 rgba(11, 40, 79, 80), stop:0.616915 rgba(49, 91, 255, 80), stop:0.686567 rgba(0, 36, 73, 80), stop:0.810945 rgba(0, 25, 82, 156), stop:1 rgba(255, 255, 255, 0));\n"
"color: black; /* 设置鼠标悬停时的文本颜色 */ \n"
"box-shadow: 5px 5px 10px rgba(10, 10, 255, 10); /* 设置鼠标悬停时的阴影效果 */ \n"
"cursor: pointer; /* 设置鼠标悬停时的指针样式 */ } \n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(40, 560, 171, 71))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(31, 164, 1021, 351))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_10.raise_()
        self.label_12.raise_()
        self.label_11.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.formLayoutWidget.raise_()
        self.label_7.raise_()
        self.verticalLayoutWidget.raise_()

        self.retranslateUi(Dialog)
        self.pushButton_3.clicked.connect(Dialog.SwitchCar) # type: ignore
        self.pushButton.clicked.connect(Dialog.ReturnChoose_2) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "东向"))
        self.label_4.setText(_translate("Dialog", "南向"))
        self.label_5.setText(_translate("Dialog", "当前人流量："))
        self.label_6.setText(_translate("Dialog", "当前状况："))
        self.label_8.setText(_translate("Dialog", "0"))
        self.label_9.setText(_translate("Dialog", "畅通"))
        self.label_7.setText(_translate("Dialog", "人流量监控系统"))
        self.pushButton_3.setText(_translate("Dialog", "跳转"))
        self.pushButton.setText(_translate("Dialog", "返回"))
